version: '3.1'
volumes:
  checkmk:

services:
  checkmk:  
    image: "checkmk/check-mk-raw:2.0.0-latest"
    restart: always    
    dns:
      - "8.8.8.8"
      - "1.1.1.1" 
    container_name: checkmkv2
    restart: always
#    volumes:
#      checkmk:/cmk    
    ports:
      - '8080:5000'

